### ISSUE TITLE
use pygame-ce

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/Pygame-intro#1]
https://github.com/tokitou-san/Pygame-intro/blob/e18796963b9fb88480d0b0b80323efba41006993/pyproject.toml#L10

**Comment by stabldev** [comment]
https://www.reddit.com/r/pygame/comments/111u3xa/comment/j8j8vjj/?utm_source=share&utm_medium=web2x&context=3
Gonna make a ce fork of Skeleton? lol

**Comment by baseplate-admin** [comment]
https://www.youtube.com/watch?v=pYq9edSUaOw&t=1s&pp=ygUYcHlnYW1lIGNlIGRhZmx1ZmZ5cG90YXRv
